# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
after_success:
    - Rscript -e "covr::codecov(token = '8bf43bea-4299-4637-b646-1564e3549536')"
