---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# BrandsEyeR2

BrandsEyeR2 is a library for handling data in your BrandsEye account.

[BrandsEye][brandseye] is an opinion mining company. We use public social media
to discover what people are talking about, and the sentiment towards these topics.
While we have an analytics suite, and reporting service, we also providean extensive API
to access to the data that makes up your various BrandsEye accounts, and makes it easy to
access the data outside of the BrandsEye application in any [R][R] analyses that you might want to
perform.

This version of the library is still in its early stages, and you should definitely be 
using the first version instead, which is available from [GitHub][brandseyer].

The goal of this version of the library is:

- to fully support our new API, 
- to better support the tidy universe of libraries
- and to have a test suite.

# Code of Conduct

Please note that this project is released with a [Contributor Code of Conduct](CODE_OF_CONDUCT.md).
By participating in this project you agree to abide by its terms.

# License

This library is licensed under the MIT, and is copyright Brandseye PTY (LTD). 


[brandseyer]: https://github.com/brandseye/brandseyer  "The original brandseyer library"
[R]: http://www.r-project.org/
[brandseye]: http://www.brandseye.com
